<?php
return array (
  'perkeoap' => 
  array (
    'base' => 'https://vacationrental-v10.ddev.site/autogenerated-1',
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'German',
        'enabled' => false,
        'languageId' => 0,
        'base' => '/',
        'typo3Language' => 'de',
        'locale' => 'de_DE.utf8',
        'iso-639-1' => 'de',
        'navigationTitle' => 'German',
        'hreflang' => 'de-De',
        'direction' => 'ltr',
        'flag' => 'de',
        'websiteTitle' => 'Perkeo Apartments',
      ),
    ),
    'rootPageId' => 1,
    'routes' => 
    array (
      0 => 
      array (
        'route' => 'robots.txt',
        'type' => 'staticText',
        'source' => '',
      ),
    ),
    'websiteTitle' => 'Perkeo Apartments',
  ),
);
#